name: Test on PR

on:
  pull_request:
   branches:
       - master

jobs:
  test:
    name: Teste infra on PR
    runs-on: ubuntu-20.04  #ubuntu-lastest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-2
    
    #- name: Build Lambda Package
    #  run: |
    #   sh Project_Rais/scripts/build_lambda_package.sh 

    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd Project_Rais/IAC
        $COMMAND_IAC init 
        $COMMAND_IAC validate
        $COMMAND_IAC plan
        
